openapi: 3.0.0
info:
  title: Vibely API
  description: API dành cho mạng xã hội học tập Vibely
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /auth/login:
    post:
      summary: "Đăng nhập"
      description: "API dùng để đăng nhập"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: "Đăng nhập thành công"
        "400":
          description: "Lỗi dữ liệu đầu vào"

  /auth/register:
    post:
      summary: "Đăng ký tài khoản"
      description: "API dùng để đăng ký tài khoản"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: "Đăng ký thành công"
        "400":
          description: "Lỗi dữ liệu đầu vào"

  /posts:
    get:
      summary: "Lấy danh sách bài viết"
      description: "API trả về danh sách bài viết"
      responses:
        "200":
          description: "Danh sách bài viết"
    post:
      summary: "Tạo bài viết mới"
      description: "API dùng để tạo bài viết mới"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
      responses:
        "201":
          description: "Bài viết đã được tạo"

  /stories:
    get:
      summary: "Lấy danh sách stories"
      description: "API trả về danh sách stories"
      responses:
        "200":
          description: "Danh sách stories"
    post:
      summary: "Tạo story mới"
      description: "API dùng để tạo story mới"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                imageUrl:
                  type: string
      responses:
        "201":
          description: "Story đã được tạo thành công"
          
  /posts/reacts/{postId}:
    post:
      summary: "Bày tỏ cảm xúc với bài viết"
      description: "API cho phép người dùng thích, yêu thích, hoặc phản ứng với bài viết"
      parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: string
          description: "ID của bài viết"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  enum: ["like", "love", "haha", "wow", "sad", "angry"]
                  description: "Loại cảm xúc"
      responses:
        "200":
          description: "Cảm xúc đã được cập nhật"
        "400":
          description: "Dữ liệu không hợp lệ"
        "404":
          description: "Không tìm thấy bài viết"
