services:
  backend:
    image: backend
    ports:
      - "8080:8080"
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env

  socket:
    image: socket
    ports:
      - "8900:8900"
    volumes:
      - ./socket:/app
      - /app/node_modules
    depends_on:
      - backend

  frontend-user:
    image: frontend-user
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-user:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend

  frontend-admin:
    image: frontend-admin
    ports:
      - "3001:3001"
    volumes:
      - ./frontend-admin:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  logs: