FROM node:18

WORKDIR /app

# Copy package files first to leverage Docker cache
COPY frontend-user/package*.json ./

# Install dependencies
RUN npm install
RUN npm install --save-dev jest selenium-webdriver @babel/register jest-html-reporters

# Copy source code after installing dependencies
COPY frontend-user/ ./
COPY tests/ ./tests/

# Create reports directory
RUN mkdir -p reports

# Command to run tests
CMD ["npm", "run", "test:ui"]