openai:
    api_key: ""
weaviate:
    url: "https://zqrky2anqfcgik6bqpvznq.c0.asia-southeast1.gcp.weaviate.cloud"
    api_key: "VjKouiVK14YFaCNeTFFgbesxd72xReZP8kur"
mongodb:
    url: "mongodb+srv://vonhatphuongahihi:13032004@cluster0.0dh0h.mongodb.net/test?retryWrites=true&w=majority&appName=Cluster0"