apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  PORT: "8081"
  NODE_ENV: "production"
  FRONTEND_URL: "http://localhost:3000"
  NEXT_PUBLIC_BACKEND_URL: "https://vibely-study-social-web.onrender.com"
  URL: "http://localhost:3000"
