apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socket
  template:
    metadata:
      labels:
        app: socket
    spec:
      containers:
        - name: socket
          image: socket
          ports:
            - containerPort: 8900
