name: Build and Push Multiple Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: vonhatphuongahihi/vibely-backend:latest
          build-args: |
            NODE_ENV=production
            MONGO_URI_ATLAS=${{ secrets.MONGO_URI_ATLAS }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            FRONTEND_URL=http://localhost:3000
            CLOUDINARY_NAME=${{ secrets.CLOUDINARY_NAME }}
            CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}
            CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}
            EMAIL_USER=${{ secrets.EMAIL_USER }}
            EMAIL_PASS=${{ secrets.EMAIL_PASS }}
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
            GOOGLE_CALLBACK_URL=http://localhost:8081/auth/google/callback

      - name: Build and push frontend-admin
        uses: docker/build-push-action@v5
        with:
          context: ./frontend-admin
          push: true
          tags: vonhatphuongahihi/vibely-frontend-admin:latest
          build-args: |
            NEXT_PUBLIC_BACKEND_URL=http://localhost:8081

      - name: Build and push frontend-user
        uses: docker/build-push-action@v5
        with:
          context: ./frontend-user
          push: true
          tags: vonhatphuongahihi/vibely-frontend-user:latest
          build-args: |
            NEXT_PUBLIC_BACKEND_URL=http://localhost:8081
